export type InputType = 'checkbox'
            | 'color'
            | 'date'
            | 'datetime-local'
            | 'email'
            | 'file'
            | 'image'
            | 'month'
            | 'number'
            | 'password'
            | 'radio'
            | 'range'
            | 'search'
            | 'tel'
            | 'text'
            | 'time'
            | 'url'
            | 'week';